CREATE TABLE GROUPMATES (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age TEXT NOT NULL,
  adress TEXT NOT NULL

);

INSERT INTO GROUPMATES VALUES (0001, 'Ivan', '22', 'Moscow');
INSERT INTO GROUPMATES VALUES (0002, 'Fedor', '28', 'Kazan');
INSERT INTO GROUPMATES VALUES (0003, 'Igor', '45', 'Ryzan');
INSERT INTO GROUPMATES VALUES (0004, 'Sergei', '37', 'Saratov');
INSERT INTO GROUPMATES VALUES (0005, 'Slava', '25', 'Penza');
INSERT INTO GROUPMATES VALUES (0006, 'Sasha', '30', 'Moscow');
INSERT INTO GROUPMATES VALUES (0007, 'Eva', '26', 'Moscow');
INSERT INTO GROUPMATES VALUES (0008, 'Tanya', '18', 'Moscow');
INSERT INTO GROUPMATES VALUES (0009, 'Sveta', '24', 'Moscow');
INSERT INTO GROUPMATES VALUES (00010, 'Olya', '33', 'Moscow');


SELECT name FROM GROUPMATES
WHERE age >= 18 AND age < 30 AND adress = 'Moscow'